# Generated by Django 2.0.7 on 2018-08-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corso', models.CharField(max_length=80)),
                ('img_corso', models.ImageField(blank=True, null=True, upload_to='')),
                ('descrizione_corso', models.CharField(blank=True, max_length=150, null=True)),
                ('docente_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lezione', models.CharField(max_length=80)),
                ('data_lezione', models.DateTimeField(auto_now_add=True)),
                ('link_lezione', models.URLField()),
                ('corso_lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lezioni', to='core.Corso')),
            ],
            options={
                'verbose_name': 'Lezione',
                'verbose_name_plural': 'Lezioni',
            },
        ),
    ]
