# Generated by Django 2.0.7 on 2018-08-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180804_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mooc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mooc', models.CharField(max_length=80)),
                ('link_mooc', models.URLField()),
                ('autore_mooc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docenti_mooc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
