# Generated by Django 2.0.7 on 2018-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mooc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mooc',
            options={'verbose_name': 'Mooc', 'verbose_name_plural': 'Mooc'},
        ),
        migrations.AddField(
            model_name='mooc',
            name='allegati_mooc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mooc',
            name='descrizione_mooc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mooc',
            name='link_mooc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
