# Generated by Django 2.0.7 on 2018-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180809_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='sezione_corso',
            field=models.CharField(blank=True, choices=[('1', 'Orientamento'), ('2', 'Impresa'), ('3', 'Digitale')], max_length=1, null=True),
        ),
    ]
