# Generated by Django 2.0.7 on 2018-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_corso_sezione_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooc',
            name='allegati_mooc',
            field=models.FileField(blank=True, null=True, upload_to='allegati_mooc/%Y/%M/'),
        ),
    ]
