# Generated by Django 2.0.7 on 2018-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180812_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='data_lezione',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
