# Generated by Django 2.0.7 on 2018-08-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_lezione_data_lezione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Corso')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferito',
                'verbose_name_plural': 'Preferiti',
            },
        ),
        migrations.RemoveField(
            model_name='mooc',
            name='autore_mooc',
        ),
        migrations.DeleteModel(
            name='Mooc',
        ),
    ]
