# Generated by Django 2.0.7 on 2018-08-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180824_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferiti',
            name='nome_corso',
        ),
        migrations.RemoveField(
            model_name='preferiti',
            name='utente',
        ),
        migrations.DeleteModel(
            name='Preferiti',
        ),
    ]
