# Generated by Django 2.0.7 on 2018-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_corso_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corso',
            name='programma_corso',
        ),
        migrations.AddField(
            model_name='corso',
            name='allegati_corso',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='corso',
            name='descrizione_corso',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
