# Generated by Django 2.0.7 on 2018-08-26 16:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180826_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='allegato_lezione',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_lezioni),
        ),
        migrations.AlterField(
            model_name='corso',
            name='allegati_corso',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi),
        ),
        migrations.AlterField(
            model_name='corso',
            name='img_corso',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi),
        ),
    ]
