# Generated by Django 2.0.7 on 2018-08-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180826_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='descrizione_corso',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
