# Generated by Django 2.0.7 on 2018-09-07 11:23

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180826_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='img_corso',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='link_lezione',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code di Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -]+$')]),
        ),
    ]
