# Generated by Django 2.0.7 on 2018-09-23 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180920_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezione',
            name='link_lezione',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -?!]+$')]),
        ),
    ]
