# Generated by Django 2.0.7 on 2018-09-25 14:53

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180923_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='allegati_corso',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi, validators=[django.core.validators.RegexValidator(message='Inserire un file in formato .pdf', regex='^.+[.]pdf')], verbose_name='Scheda Tecnica'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='link_lezione',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -?!\\n]+$')]),
        ),
    ]
