# Generated by Django 2.0.7 on 2019-01-06 11:41

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0019_auto_20180925_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome_contenuto', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_lezioni)),
            ],
            options={
                'verbose_name': 'Contenuto',
                'verbose_name_plural': 'Contenuti',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome_contenuto', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -?!\\n]+$')])),
            ],
            options={
                'verbose_name': 'Contenuto',
                'verbose_name_plural': 'Contenuti',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lezione',
            name='contenuto',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('filepdf', 'linkvideo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
