# Generated by Django 2.2 on 2019-04-12 13:25

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_risorsa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepdf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='linkvideo',
            options={},
        ),
        migrations.RemoveField(
            model_name='lezione',
            name='contenuto',
        ),
        migrations.RemoveField(
            model_name='risorsa',
            name='contenuto',
        ),
        migrations.AddField(
            model_name='lezione',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_lezioni),
        ),
        migrations.AddField(
            model_name='lezione',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -?!\\n]+$')]),
        ),
    ]
