# Generated by Django 2.0.7 on 2019-05-15 17:47

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190412_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezione',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_lezioni, validators=[django.core.validators.RegexValidator(message='Inserire un file in formato .pdf', regex='^.+[.]pdf')]),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='link_lezione',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Inserire soltanto Embed Code Vimeo', regex='^<iframe src="https://player.vimeo.com.[a-zA-Z"./:+=0-9>< -?!\\n]+$')]),
        ),
    ]
