# Generated by Django 2.0.7 on 2019-05-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190515_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezione',
            name='link_lezione',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
