# Generated by Django 2.0.7 on 2019-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_corsoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='corsoprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
