# Generated by Django 2.0.7 on 2019-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_corsoprogress_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsoprogress',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='contenuti', to='core.Lezione'),
        ),
    ]
