# Generated by Django 2.0.7 on 2019-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190518_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corsoprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
