# Generated by Django 2.0.7 on 2019-05-23 09:06

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190518_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risorsa',
            options={'verbose_name': 'Risorsa Didattica', 'verbose_name_plural': 'Risorse Didattiche'},
        ),
        migrations.RenameField(
            model_name='risorsa',
            old_name='nome',
            new_name='nome_lezione',
        ),
        migrations.RemoveField(
            model_name='lezione',
            name='allegato_lezione',
        ),
        migrations.RemoveField(
            model_name='lezione',
            name='file',
        ),
        migrations.RemoveField(
            model_name='lezione',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lezione',
            name='link_lezione',
        ),
        migrations.RemoveField(
            model_name='risorsa',
            name='corso',
        ),
        migrations.AddField(
            model_name='risorsa',
            name='allegato_lezione',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_lezioni),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='link_lezione',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='nome_lezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risorse', to='core.Risorsa'),
        ),
    ]
