# Generated by Django 2.0.8 on 2019-05-28 11:21

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190523_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='allegati_corso',
            field=models.FileField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi, validators=[django.core.validators.RegexValidator(message='Inserire un file in formato .pdf', regex='^.+[.]pdf'), core.models.file_size], verbose_name='Scheda Tecnica'),
        ),
        migrations.AlterField(
            model_name='corso',
            name='img_corso',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.percorso_cartella_corsi, validators=[core.models.file_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='allegato_lezione',
            field=models.FileField(blank=True, null=True, upload_to=core.models.cartelle_risorse, validators=[core.models.file_size]),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='link_lezione',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='nome_lezione',
            field=models.CharField(max_length=100),
        ),
    ]
