# Generated by Django 2.0.7 on 2018-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='genere',
            field=models.CharField(blank=True, choices=[('f', 'femmina'), ('m', 'maschio')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='scuola',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
