# Generated by Django 2.0.7 on 2018-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180824_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='preferiti',
        ),
    ]
