# Generated by Django 2.0.7 on 2018-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180824_1246'),
        ('index', '0004_remove_utente_preferiti'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='preferiti',
            field=models.ManyToManyField(related_name='corsi_seguiti', to='core.Corso'),
        ),
    ]
