# Generated by Django 2.0.7 on 2018-09-20 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180920_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='scuola',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Inserire il Codice Meccanografico della propria scuola, accertandosi che le prime due lettere inserite siano delle maiuscole', regex='^[A-Z][0-9]*')], verbose_name='Codice Meccanografico'),
        ),
    ]
