# Generated by Django 2.0.7 on 2018-09-24 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180920_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scuola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_scuola', models.CharField(blank=True, max_length=200, null=True)),
                ('regione', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('codice', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Inserire il Codice Meccanografico della propria scuola, accertandosi che le prime due lettere inserite siano delle maiuscole', regex='^[A-Z][0-9]*')], verbose_name='Codice Meccanografico')),
            ],
            options={
                'verbose_name': 'Scuola',
                'verbose_name_plural': 'Scuole',
            },
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.RemoveField(
            model_name='utente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='regione',
        ),
        migrations.AlterField(
            model_name='utente',
            name='scuola',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Scuola'),
        ),
    ]
