# Generated by Django 2.0.7 on 2018-09-25 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0009_auto_20180924_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuola',
            name='docenti_scuola',
            field=models.ManyToManyField(blank=True, null=True, related_name='Docenti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utente',
            name='scuola',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Inserire il Codice Meccanografico della propria scuola, accertandosi che le prime due lettere inserite siano delle maiuscole', regex='^[A-Z][0-9]*')], verbose_name='Codice Meccanografico'),
        ),
    ]
