# Generated by Django 2.2 on 2019-04-12 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180925_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scuola',
            name='docenti_scuola',
            field=models.ManyToManyField(related_name='Docenti', to=settings.AUTH_USER_MODEL),
        ),
    ]
