# Generated by Django 2.0.8 on 2019-05-31 13:55

import django.core.validators
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='picture',
            field=models.ImageField(upload_to=index.models.percorso_cartella_utenti, validators=[index.models.file_size]),
        ),
        migrations.AlterField(
            model_name='utente',
            name='scuola',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Inserire il Codice Meccanografico della propria scuola, accertandosi che le prime due lettere inserite siano delle maiuscole', regex='^[A-Z][0-9]*')], verbose_name='Codice Meccanografico'),
        ),
    ]
